"""Package initialization for the support module."""

from .database import Database, Record, Table, load_substitutions, resolve_manager_id
from .records import (
    AbsenceFields,
    CatererFeedbackFields,
    CatererFields,
    CatererSwitchProposalFields,
    DayName,
    DeliveryFeeStructure,
    DietaryRestrictionFields,
    EmailStatus,
    ExclusionFields,
    ManagerSubstitutionFields,
    MenuItemFields,
    OnSiteManagerFields,
    OrderFields,
    ProposalStatus,
    Region,
    ScheduledEmailFields,
    SchoolFields,
    SessionFields,
    StudentFields,
    WeeklyOrderFields,
    YearLevel,
)
from .support import VERBOSE, ask_llm, log
from .error_handler import UnhandledEdgeCaseError, self_healing_error_handler
from .email import (
    Alert,
    Button,
    Card,
    Component,
    Divider,
    Heading,
    Image,
    Link,
    List,
    Meta,
    Text,
    compose_email,
    escalate_to_dev,
    html_email,
    schedule_email,
)

__all__ = [
    "AbsenceFields",
    "CatererFeedbackFields",
    "CatererFields",
    "CatererSwitchProposalFields",
    "Database",
    "DayName",
    "DeliveryFeeStructure",
    "DietaryRestrictionFields",
    "EmailStatus",
    "ExclusionFields",
    "ManagerSubstitutionFields",
    "MenuItemFields",
    "OnSiteManagerFields",
    "OrderFields",
    "ProposalStatus",
    "Record",
    "Region",
    "ScheduledEmailFields",
    "SchoolFields",
    "SessionFields",
    "StudentFields",
    "Table",
    "VERBOSE",
    "WeeklyOrderFields",
    "YearLevel",
    "Alert",
    "Button",
    "Card",
    "Component",
    "Divider",
    "Heading",
    "Image",
    "Link",
    "List",
    "Meta",
    "Text",
    "ask_llm",
    "compose_email",
    "escalate_to_dev",
    "html_email",
    "load_substitutions",
    "log",
    "resolve_manager_id",
    "schedule_email",
    "UnhandledEdgeCaseError",
    "self_healing_error_handler",
]

