"""Package initialization for the support module."""

from .database import Database, Record, Table, load_substitutions, resolve_manager_id
from .records import (
    AbsenceFields,
    CatererFeedbackFields,
    CatererFields,
    CatererSwitchProposalFields,
    DayName,
    DeliveryFeeStructure,
    DietaryRestrictionFields,
    EmailStatus,
    ExclusionFields,
    ManagerSubstitutionFields,
    MenuItemFields,
    OnSiteManagerFields,
    OrderFields,
    ProposalStatus,
    Region,
    ScheduledEmailFields,
    SchoolFields,
    SessionFields,
    StudentFields,
    WeeklyOrderFields,
    YearLevel,
)
from .support import VERBOSE, ask_llm, log
from .error_handler import UnhandledEdgeCaseError, self_healing_error_handler

__all__ = [
    "AbsenceFields",
    "CatererFeedbackFields",
    "CatererFields",
    "CatererSwitchProposalFields",
    "Database",
    "DayName",
    "DeliveryFeeStructure",
    "DietaryRestrictionFields",
    "EmailStatus",
    "ExclusionFields",
    "ManagerSubstitutionFields",
    "MenuItemFields",
    "OnSiteManagerFields",
    "OrderFields",
    "ProposalStatus",
    "Record",
    "Region",
    "ScheduledEmailFields",
    "SchoolFields",
    "SessionFields",
    "StudentFields",
    "Table",
    "VERBOSE",
    "WeeklyOrderFields",
    "YearLevel",
    "ask_llm",
    "load_substitutions",
    "log",
    "resolve_manager_id",
    "UnhandledEdgeCaseError",
    "self_healing_error_handler",
]

