"""
evaluate_caterers.py — Check rolling caterer ratings and propose switches.

For each (school, caterer) pair with enough rated sessions:
  - avg ≤ SWITCH_THRESHOLD and raters ≥ MIN_RATERS  → create a switch proposal
    and queue a notification email to the school's on-site manager(s)
  - avg ≤ WATCH_THRESHOLD (but > SWITCH_THRESHOLD)  → queue a warning email only

Duplicate suppression (per term):
  - Skips pairs that already have a Pending / Approved / Executed proposal.
  - Skips pairs whose most-recent proposal was Rejected during the current
    Queensland school term (so the manager doesn't receive the same alert
    every week for the rest of the term after they've reviewed and declined).

Dietary hard filter: a candidate caterer is only eligible if it has at least
one compatible menu item for EVERY non-opted-out student at the school.
Even a single uncoverable student disqualifies the candidate entirely.

Usage:
  python scripts/actions/evaluate_caterers.py [--dry-run]
"""

import argparse
import os
from collections import defaultdict
from datetime import date, timedelta

import support as s
from support.compatibility import build_hierarchy, has_opted_out, is_item_compatible

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SWITCH_THRESHOLD = 2.5   # propose a caterer switch
WATCH_THRESHOLD  = 3.0   # warn coordinator only (no proposal)
MIN_SESSIONS     = 3     # minimum distinct sessions with feedback to fire SWITCH
MIN_RATERS       = 5     # minimum unique students rating in the window for SWITCH
ROLLING_WINDOW   = 4     # most-recent N sessions to average over

# Approximate Queensland school term starts for 2026.
# Update each year or replace with a config file.
QLD_TERM_STARTS = [
    date(2026, 1, 27),
    date(2026, 4, 20),
    date(2026, 7, 14),
    date(2026, 10, 5),
]


# ---------------------------------------------------------------------------
# Term helpers
# ---------------------------------------------------------------------------

def get_term_start(today=None):
    """Return the start date of the current QLD school term."""
    if today is None:
        today = date.today()
    term_start = QLD_TERM_STARTS[0]
    for ts in QLD_TERM_STARTS:
        if ts <= today:
            term_start = ts
    return term_start


def get_effective_week():
    """Return the Monday of the week *after* next — the earliest week the
    switch can affect (next week's order was just generated by register_orders).
    """
    today = date.today()
    days_to_monday = (7 - today.weekday()) % 7 or 7
    next_monday = today + timedelta(days=days_to_monday)
    return next_monday + timedelta(days=7)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_data():
    s.log.info("Loading data from Airtable...")
    data = {
        "sessions":             s.airtable_get("Sessions"),
        "feedback":             s.airtable_get("Caterer Feedback"),
        "caterers":             s.airtable_get("Caterers"),
        "students":             s.airtable_get("Students"),
        "menu_items":           s.airtable_get("Menu Items"),
        "dietary_restrictions": s.airtable_get("Dietary Restrictions"),
        "proposals":            s.airtable_get("Caterer Switch Proposals"),
        "schools":              s.airtable_get("Schools"),
        "managers":             s.airtable_get("On-Site Managers"),
    }
    s.log.info(
        f"Loaded: {len(data['sessions'])} sessions, "
        f"{len(data['feedback'])} feedback records, "
        f"{len(data['caterers'])} caterers"
    )
    return data


# ---------------------------------------------------------------------------
# Index builders
# ---------------------------------------------------------------------------

def build_session_index(sessions):
    """
    Returns:
        session_to_school   — {session_id: school_id}
        session_to_caterer  — {session_id: caterer_id}
        session_to_date     — {session_id: iso_date_str}
        school_to_sessions  — {school_id: [session_id, ...]}
        school_to_caterer   — {school_id: caterer_id}  (current active caterer)
    """
    session_to_school  = {}
    session_to_caterer = {}
    session_to_date    = {}
    school_to_sessions = defaultdict(list)
    school_to_caterer  = {}

    for rec in sessions:
        sid = rec["id"]
        f   = rec["fields"]
        school_id  = (f.get("School")  or [None])[0]
        caterer_id = (f.get("Caterer") or [None])[0]
        date_v     = f.get("Date")

        if school_id:
            session_to_school[sid] = school_id
            school_to_sessions[school_id].append(sid)
            if caterer_id:
                school_to_caterer[school_id] = caterer_id
        if caterer_id:
            session_to_caterer[sid] = caterer_id
        if date_v:
            session_to_date[sid] = date_v

    return (session_to_school, session_to_caterer, session_to_date,
            school_to_sessions, school_to_caterer)


def build_feedback_index(feedback_list, session_to_school, session_to_date):
    """
    Group feedback by (school_id, caterer_id).
    Each entry: (date_str, session_id, rating, student_id)
    Sorted by date ascending so the tail is the most recent.

    If a feedback record lacks Session Date (legacy), falls back to the
    session's representative Date field (less precise but workable).
    """
    index        = defaultdict(list)
    legacy_count = 0
    skipped      = 0
    for fb in feedback_list:
        f          = fb["fields"]
        rating     = f.get("Rating")
        caterer_id = (f.get("Caterer") or [None])[0]
        student_id = (f.get("Student") or [None])[0]
        session_id = (f.get("Session") or [None])[0]
        if rating is None or not caterer_id or not session_id:
            skipped += 1
            s.log.verbose(
                f"Skipping feedback {fb['id']}: "
                f"rating={rating} caterer={caterer_id} session={session_id}"
            )
            continue
        school_id = session_to_school.get(session_id)
        if not school_id:
            skipped += 1
            s.log.verbose(f"Skipping feedback {fb['id']}: session {session_id} has no school")
            continue
        explicit_date = f.get("Session Date")
        if not explicit_date:
            legacy_count += 1
        date_str = explicit_date or session_to_date.get(session_id) or ""
        s.log.verbose(
            f"Feedback {fb['id']}: school={school_id} caterer={caterer_id} "
            f"rating={rating} date={date_str!r} {'(legacy date)' if not explicit_date else ''}"
        )
        index[(school_id, caterer_id)].append((date_str, session_id, rating, student_id))

    for key in index:
        index[key].sort(key=lambda x: x[0])

    s.log.verbose(
        f"Feedback index built: {sum(len(v) for v in index.values())} entries across "
        f"{len(index)} (school, caterer) pair(s); {legacy_count} legacy-date, {skipped} skipped"
    )
    return index


def build_menu_index(menu_items):
    """Returns {caterer_id: [{"id": ..., "fields": ...}, ...]}"""
    by_caterer = defaultdict(list)
    for item in menu_items:
        for cid in (item["fields"].get("Caterer") or []):
            by_caterer[cid].append({"id": item["id"], "fields": item["fields"]})
    return by_caterer


def build_school_name_index(schools):
    return {r["id"]: r["fields"].get("School Name", r["id"]) for r in schools}


def build_caterer_name_index(caterers):
    return {r["id"]: r["fields"].get("Caterer Name", r["id"]) for r in caterers}


def build_manager_index(managers):
    """Returns {manager_id: email_str_or_None}"""
    return {r["id"]: r["fields"].get("Email") for r in managers}


def get_school_manager_email(school_id, sessions, manager_index):
    """
    Return the email of the first on-site manager found for any session at
    this school, or None if no manager has an email on record.
    """
    for sess in sessions:
        if school_id not in (sess["fields"].get("School") or []):
            continue
        for mgr_id in (sess["fields"].get("On-Site Manager") or []):
            email = manager_index.get(mgr_id)
            if email:
                return email
    return None


# ---------------------------------------------------------------------------
# Rolling stats
# ---------------------------------------------------------------------------

def get_rolling_stats(entries):
    """
    Given sorted (date_str, session_id, rating, student_id) entries for a
    (school, caterer) pair, return (num_sessions, avg_rating, num_raters)
    for the most recent ROLLING_WINDOW distinct sessions.

    Returns None if fewer than MIN_SESSIONS distinct sessions have feedback.
    """
    by_session = defaultdict(lambda: {"ratings": [], "students": set(), "date": ""})
    for date_str, session_id, rating, student_id in entries:
        by_session[session_id]["ratings"].append(rating)
        by_session[session_id]["students"].add(student_id)
        if date_str > by_session[session_id]["date"]:
            by_session[session_id]["date"] = date_str

    sessions_sorted = sorted(by_session.items(), key=lambda x: x[1]["date"])
    s.log.verbose(
        f"  Sessions with feedback (oldest→newest): "
        + ", ".join(
            f"{sid[:8]}… avg={sum(d['ratings'])/len(d['ratings']):.1f} "
            f"({len(d['ratings'])} ratings, date={d['date']!r})"
            for sid, d in sessions_sorted
        )
    )

    window = sessions_sorted[-ROLLING_WINDOW:]

    # if len(window) < MIN_SESSIONS:
    #     s.log.verbose(
    #         f"  Only {len(window)} session(s) in window — need {MIN_SESSIONS}; skipping"
    #     )
    #     return None

    all_ratings = []
    all_raters  = set()
    for sid, data in window:
        all_ratings.extend(data["ratings"])
        all_raters.update(data["students"])
        s.log.verbose(
            f"  Window session {sid[:8]}…: "
            f"ratings={data['ratings']} students={len(data['students'])}"
        )

    avg = sum(all_ratings) / len(all_ratings)
    s.log.verbose(
        f"  Rolling window: {len(window)} sessions, "
        f"avg={avg:.2f}, raters={len(all_raters)}"
    )
    return len(window), avg, len(all_raters)


# ---------------------------------------------------------------------------
# Dietary coverage check (hard filter)
# ---------------------------------------------------------------------------

def caterer_covers_all_students(caterer_id, school_students, menu_by_caterer, hierarchy):
    """
    Return (True, None) if every non-opted-out student at the school has at
    least one compatible menu item with this caterer.
    Return (False, student_name) on the first student who can't be covered.
    """
    caterer_menu = menu_by_caterer.get(caterer_id, [])
    if not caterer_menu:
        return False, "(no menu items on record)"

    s.log.verbose(
        f"  Dietary check: {len(caterer_menu)} menu item(s), "
        f"{len(school_students)} student(s)"
    )
    for stu in school_students:
        dietary_ids = stu["fields"].get("Dietary Requirements") or []
        if has_opted_out(dietary_ids, hierarchy):
            s.log.verbose(
                f"    Skipping opted-out student "
                f"'{stu['fields'].get('Student Name', stu['id'])}'"
            )
            continue
        any_ok = any(
            is_item_compatible(item["fields"], dietary_ids, hierarchy)
            for item in caterer_menu
        )
        s.log.verbose(
            f"    Student '{stu['fields'].get('Student Name', stu['id'])}' "
            f"({len(dietary_ids)} requirement(s)): {'OK' if any_ok else 'NO MATCH'}"
        )
        if not any_ok:
            return False, stu["fields"].get("Student Name", "unknown student")

    return True, None


# ---------------------------------------------------------------------------
# Candidate scoring and selection
# ---------------------------------------------------------------------------

def score_candidate(caterer_id, school_id, feedback_index, caterer_names):
    """
    score = 0.6 * avg_at_this_school + 0.4 * avg_overall
    If the caterer has no history at this school, score = avg_overall.
    Default overall average is 3.0 (neutral) when no history exists at all.
    """
    school_entries = feedback_index.get((school_id, caterer_id), [])
    all_entries    = [
        entry
        for (sid, cid), entries in feedback_index.items()
        if cid == caterer_id
        for entry in entries
    ]

    all_ratings    = [r for _, _, r, _ in all_entries]
    school_ratings = [r for _, _, r, _ in school_entries]

    avg_overall = sum(all_ratings) / len(all_ratings) if all_ratings else 3.0

    if school_ratings:
        avg_school = sum(school_ratings) / len(school_ratings)
        score      = 0.6 * avg_school + 0.4 * avg_overall
        s.log.verbose(
            f"  Score for '{caterer_names.get(caterer_id, caterer_id)}': "
            f"school_avg={avg_school:.2f} ({len(school_ratings)} ratings), "
            f"overall_avg={avg_overall:.2f} ({len(all_ratings)} ratings) → score={score:.2f}"
        )
        return score

    s.log.verbose(
        f"  Score for '{caterer_names.get(caterer_id, caterer_id)}': "
        f"no history at school, overall_avg={avg_overall:.2f} "
        f"({len(all_ratings)} ratings) → score={avg_overall:.2f}"
    )
    return avg_overall


def find_candidates(school_id, outgoing_caterer_id, caterers,
                    school_students, menu_by_caterer, hierarchy,
                    feedback_index, caterer_names):
    """
    Return sorted list of (score, caterer_id, caterer_name) for eligible
    replacement caterers — those where school_id is in Able to Serve Schools
    AND every non-opted-out student has a compatible meal.
    """
    candidates = []
    for cat in caterers:
        cid = cat["id"]
        if cid == outgoing_caterer_id:
            continue
        able = cat["fields"].get("Able to Serve Schools") or []
        if school_id not in able:
            continue

        covered, failing = caterer_covers_all_students(
            cid, school_students, menu_by_caterer, hierarchy
        )
        if not covered:
            s.log.info(
                f"  Candidate '{caterer_names[cid]}' excluded: "
                f"no compatible meal for '{failing}'"
            )
            continue

        score = score_candidate(cid, school_id, feedback_index, caterer_names)
        candidates.append((score, cid, caterer_names[cid]))

    candidates.sort(key=lambda x: -x[0])
    return candidates


# ---------------------------------------------------------------------------
# Existing-proposal checks
# ---------------------------------------------------------------------------

def has_active_proposal(school_id, caterer_id, proposals):
    """True if a Pending / Approved / Executed proposal already exists."""
    for p in proposals:
        f = p["fields"]
        if school_id not in (f.get("School") or []):
            continue
        if caterer_id not in (f.get("Outgoing Caterer") or []):
            continue
        if f.get("Status") in ("Pending", "Approved", "Executed"):
            return True
    return False


def was_rejected_this_term(school_id, caterer_id, proposals, term_start):
    """True if a Rejected proposal for this pair exists since term_start."""
    term_start_str = term_start.isoformat()
    for p in proposals:
        f = p["fields"]
        if school_id not in (f.get("School") or []):
            continue
        if caterer_id not in (f.get("Outgoing Caterer") or []):
            continue
        if f.get("Status") != "Rejected":
            continue
        if (f.get("Proposed On") or "") >= term_start_str:
            return True
    return False


# ---------------------------------------------------------------------------
# Email formatting
# ---------------------------------------------------------------------------

def format_proposal_email(school_name, outgoing_name, incoming_name,
                          avg_rating, num_sessions, num_raters, effective_week,
                          proposal_url):
    action_line = (
        f"[Review, approve, or reject this proposal]({proposal_url})"
        if proposal_url else
        "Open **Caterer Switch Proposals** in Airtable to approve or reject."
    )
    return (
        f"Hi,\n\n"
        f"The automated rating check has flagged **{outgoing_name}** at "
        f"**{school_name}**.\n\n"
        f"**Rolling average:** {avg_rating:.1f}/5 "
        f"over the last {num_sessions} sessions\n"
        f"**Sampled from:** {num_raters} students\n\n"
        f"**Proposed replacement:** {incoming_name}\n\n"
        f"**Effective week:** {effective_week.strftime('%-d %B %Y')}\n\n"
        f"{action_line}\n\n"
        f"Approving will schedule the switch for the effective week above. "
        f"Rejecting means you won't be reminded about this caterer again this term.\n\n"
        f"— Padea automation"
    )


def format_no_candidate_email(school_name, outgoing_name, avg_rating,
                              num_sessions, num_raters):
    return (
        f"Hi,\n\n"
        f"The automated rating check has flagged **{outgoing_name}** at "
        f"**{school_name}** (average {avg_rating:.1f}/5 over "
        f"{num_sessions} sessions, {num_raters} raters), but "
        f"**no eligible replacement caterer was found**.\n\n"
        f"Please review the situation manually:\n"
        f"- Check whether any caterer's *Able to Serve Schools* list "
        f"needs updating.\n"
        f"- Check whether any menu items need to be added for existing caterers.\n\n"
        f"— Padea automation"
    )


def format_watch_email(school_name, caterer_name, avg_rating,
                       num_sessions, num_raters):
    return (
        f"Hi,\n\n"
        f"**{caterer_name}** at **{school_name}** has a rolling average of "
        f"**{avg_rating:.1f}/5** over the last {num_sessions} sessions "
        f"({num_raters} raters). This is below the watch threshold of "
        f"{WATCH_THRESHOLD}/5.\n\n"
        f"No action has been taken yet. If ratings continue to fall "
        f"below {SWITCH_THRESHOLD}/5, a switch proposal will be generated "
        f"automatically.\n\n"
        f"— Padea automation"
    )


# ---------------------------------------------------------------------------
# Proposal and email creation
# ---------------------------------------------------------------------------

def create_proposal_and_email(school_id, school_name,
                              outgoing_caterer_id, outgoing_name,
                              incoming_caterer_id, incoming_name,
                              avg_rating, num_sessions, num_raters,
                              effective_week, recipient_email, dry_run,
                              immediate):
    today       = date.today()
    proposal_id = (
        f"PROP-{school_name[:10].upper().replace(' ', '')}"
        f"-{today.isoformat()}"
    )

    proposal_fields = {
        "Proposal ID":      proposal_id,
        "School":           [school_id],
        "Outgoing Caterer": [outgoing_caterer_id],
        "Incoming Caterer": [incoming_caterer_id],
        "Avg Rating":       round(avg_rating, 2),
        "Sessions Sampled": num_sessions,
        "Unique Raters":    num_raters,
        "Proposed On":      today.isoformat(),
        "Effective Week":   effective_week.isoformat(),
        "Status":           "Pending",
    }

    subject = f"[Padea] Caterer switch proposed — {school_name}"

    if dry_run:
        url_origin = os.environ.get("URL_ORIGIN", "").rstrip("/")
        fake_url   = f"{url_origin}/switch-proposal.html?id=<record_id>" if url_origin else None
        body = format_proposal_email(school_name, outgoing_name, incoming_name,
                                     avg_rating, num_sessions, num_raters,
                                     effective_week, fake_url)
        s.log.info(f"[DRY RUN] Would create proposal: {proposal_id}")
        s.log.info(f"[DRY RUN] Would queue email to {recipient_email}: {subject}")
        s.log.info(f"[DRY RUN] Proposal URL would be: {fake_url}")
        return

    result = s.airtable_post("Caterer Switch Proposals", [proposal_fields])
    rec_id = result[0]["id"] if result else None
    s.log.info(f"Created proposal: {proposal_id} (record {rec_id})")

    if rec_id:
        url_origin    = os.environ.get("URL_ORIGIN", "").rstrip("/")
        proposal_url  = (
            f"{url_origin}/switch-proposal.html?id={rec_id}"
            if url_origin else None
        )
        if not url_origin:
            s.log.warning(
                "URL_ORIGIN not set in .env — proposal email will not include a link"
            )

        body = format_proposal_email(school_name, outgoing_name, incoming_name,
                                     avg_rating, num_sessions, num_raters,
                                     effective_week, proposal_url)

        if recipient_email:
            from send_orders import schedule_email
            schedule_email(
                to_email=recipient_email,
                cc_email=None,
                subject=subject,
                body=body,
                email_id=f"SWITCH-{proposal_id}",
                immediate=immediate,
                caterer_switch_proposal_id=rec_id,
            )


def queue_alert_email(subject, body, recipient_email, email_id, dry_run):
    if dry_run:
        s.log.info(f"[DRY RUN] Would queue alert email: {subject}")
        return
    if not recipient_email:
        s.log.warning("No on-site manager email found — skipping alert email")
        return
    from send_orders import schedule_email
    schedule_email(
        to_email=recipient_email,
        cc_email=None,
        subject=subject,
        body=body,
        email_id=email_id,
    )


# ---------------------------------------------------------------------------
# Main evaluation loop
# ---------------------------------------------------------------------------

def evaluate(dry_run=False, immediate=False):
    if immediate:
        s.log.info("Send immediately turned ON")

    data = load_data()

    hierarchy        = build_hierarchy(data["dietary_restrictions"])
    menu_by_caterer  = build_menu_index(data["menu_items"])
    school_names     = build_school_name_index(data["schools"])
    caterer_names    = build_caterer_name_index(data["caterers"])
    manager_index    = build_manager_index(data["managers"])

    (session_to_school, session_to_caterer, session_to_date,
     school_to_sessions, school_to_caterer) = build_session_index(data["sessions"])

    feedback_index = build_feedback_index(
        data["feedback"], session_to_school, session_to_date
    )

    term_start     = get_term_start()
    effective_week = get_effective_week()

    s.log.info(f"Term start: {term_start}  |  Effective week if switched: {effective_week}")

    # Build a lookup of students per school
    school_to_students = defaultdict(list)
    for stu in data["students"]:
        for sid in (stu["fields"].get("Sessions") or []):
            school_id = session_to_school.get(sid)
            if school_id:
                school_to_students[school_id].append(stu)
                break  # avoid adding the same student multiple times

    evaluated = 0
    for (school_id, caterer_id), entries in feedback_index.items():
        school_name  = school_names.get(school_id, school_id)
        caterer_name = caterer_names.get(caterer_id, caterer_id)

        s.log.verbose(f"Evaluating: {school_name} / {caterer_name} ({len(entries)} feedback entries)")
        stats = get_rolling_stats(entries)
        if stats is None:
            s.log.verbose(
                f"Skipping {school_name} / {caterer_name}: "
                f"insufficient data (< {MIN_SESSIONS} sessions)"
            )
            continue

        num_sessions, avg_rating, num_raters = stats
        evaluated += 1
        s.log.info(
            f"{school_name} / {caterer_name}: "
            f"avg={avg_rating:.2f} over {num_sessions} sessions, "
            f"{num_raters} raters"
        )

        # --- Watch threshold only ---
        if SWITCH_THRESHOLD < avg_rating <= WATCH_THRESHOLD:
            recipient = get_school_manager_email(school_id, data["sessions"], manager_index)
            subject   = f"[Padea] Caterer watch — {school_name}"
            body      = format_watch_email(school_name, caterer_name,
                                           avg_rating, num_sessions, num_raters)
            email_id  = f"WATCH-{school_id[:6]}-{caterer_id[:6]}-{date.today().isoformat()}"
            queue_alert_email(subject, body, recipient, email_id, dry_run)
            continue

        if avg_rating > WATCH_THRESHOLD:
            continue

        # --- Switch threshold ---
        if num_raters < MIN_RATERS:
            s.log.info(
                f"  Rating {avg_rating:.2f} below switch threshold but only "
                f"{num_raters}/{MIN_RATERS} raters — not enough data to propose switch"
            )
            continue

        # Check current caterer for this school matches; skip historical pairs
        current_caterer = school_to_caterer.get(school_id)
        if current_caterer != caterer_id:
            s.log.info(
                f"  {caterer_name} is no longer the active caterer at "
                f"{school_name} — skipping"
            )
            continue

        # Dedup checks
        s.log.verbose(
            f"  Checking {len(data['proposals'])} existing proposal(s) for dedup"
        )
        if has_active_proposal(school_id, caterer_id, data["proposals"]):
            s.log.info(
                f"  Active proposal already exists for {school_name} / "
                f"{caterer_name} — skipping"
            )
            continue
        if was_rejected_this_term(school_id, caterer_id, data["proposals"], term_start):
            s.log.info(
                f"  Proposal for {school_name} / {caterer_name} was rejected "
                f"this term — skipping"
            )
            continue
        s.log.verbose(f"  No blocking proposals found — proceeding with candidate search")

        s.log.info(
            f"  *** Rating {avg_rating:.2f} below switch threshold — "
            f"finding candidates ***"
        )

        school_students = school_to_students.get(school_id, [])
        candidates = find_candidates(
            school_id, caterer_id, data["caterers"],
            school_students, menu_by_caterer, hierarchy,
            feedback_index, caterer_names,
        )

        recipient = get_school_manager_email(school_id, data["sessions"], manager_index)
        if not recipient:
            s.log.warning(
                f"  No on-site manager email for {school_name} — "
                "proposals will be created but no email queued"
            )

        if not candidates:
            s.log.warning(
                f"  No eligible replacement for {caterer_name} at {school_name}"
            )
            subject  = f"[Padea] Caterer alert — no replacement for {caterer_name} at {school_name}"
            body     = format_no_candidate_email(school_name, caterer_name,
                                                 avg_rating, num_sessions, num_raters)
            email_id = f"NOCAND-{school_id[:6]}-{caterer_id[:6]}-{date.today().isoformat()}"
            queue_alert_email(subject, body, recipient, email_id, dry_run)
            continue

        best_score, best_id, best_name = candidates[0]
        s.log.info(f"  Best candidate: {best_name} (score {best_score:.2f})")

        create_proposal_and_email(
            school_id=school_id,
            school_name=school_name,
            outgoing_caterer_id=caterer_id,
            outgoing_name=caterer_name,
            incoming_caterer_id=best_id,
            incoming_name=best_name,
            avg_rating=avg_rating,
            num_sessions=num_sessions,
            num_raters=num_raters,
            effective_week=effective_week,
            recipient_email=recipient,
            dry_run=dry_run,
            immediate=immediate
        )

    s.log.info(f"Evaluation complete. {evaluated} (school, caterer) pair(s) had sufficient data.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate caterer ratings and propose switches")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Log what would happen without writing to Airtable"
    )
    parser.add_argument(
        "--immediate",
        action="store_true",
        help="Flag the email as to be sent immediately"
    )
    args = parser.parse_args()
    evaluate(dry_run=args.dry_run, immediate=args.immediate)
